      PROGRAM GXINT
*
* Author: R. Hakobyan, Z. Papandreou
*

      PARAMETER (NWGEAN=15000000,NWPAW=9000000)
      COMMON/GCBANK/GEANT(NWGEAN)
      COMMON/PAWC/PAW(NWPAW)
      CALL GPAW(NWGEAN,NWPAW)

      END
      SUBROUTINE QNEXT
      END
      SUBROUTINE CZOPEN
      END
      SUBROUTINE CZTCP
      END
      SUBROUTINE CZCLOS
      END
      SUBROUTINE CZPUTA
      END
